# Generated by Django 5.0.2 on 2024-02-26 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("author", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "published_date",
                    models.DateTimeField(unique_for_date=datetime.timezone),
                ),
            ],
        ),
    ]
