# Generated by Django 5.0.2 on 2024-02-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0002_post_updated_alter_post_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(max_length=100),
        ),
    ]
